// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(StocksContext))]
    partial class StocksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountCategory");

                    b.Property<bool>("AccountType");

                    b.Property<int?>("AccoutnParentID");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DebitLimit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TaxNum")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Telex")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AccountID");

                    b.HasIndex("AccoutnParentID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DAL.Entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DAL.Entities.Currency", b =>
                {
                    b.Property<int>("CurrencyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("CurrencyValue");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PartName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("PartValue");

                    b.HasKey("CurrencyID");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("DAL.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("BankAccNum")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("BirthDate");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsInternal");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PassportProfession")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Religion");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DAL.Entities.EmployeeCard", b =>
                {
                    b.Property<int>("EmpCardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardType");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeID");

                    b.Property<DateTime?>("EndDate");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("IssueDate");

                    b.Property<string>("IssuePlace")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("RenewalDate");

                    b.HasKey("EmpCardId");

                    b.HasIndex("EmployeeID");

                    b.ToTable("EmployeeCards");
                });

            modelBuilder.Entity("DAL.Entities.Entry", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date");

                    b.HasKey("EntryID");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("DAL.Entities.EntryDetail", b =>
                {
                    b.Property<int>("EntryDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<decimal>("Credit");

                    b.Property<decimal>("Debit");

                    b.HasKey("EntryDetailID");

                    b.HasIndex("AccountID");

                    b.ToTable("EntryDetails");
                });

            modelBuilder.Entity("DAL.Entities.Notice", b =>
                {
                    b.Property<int>("NoticeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeID");

                    b.Property<DateTime?>("NoticeDate");

                    b.Property<int>("PortfolioID");

                    b.Property<bool>("Type");

                    b.HasKey("NoticeID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("DAL.Entities.NoticeDetail", b =>
                {
                    b.Property<int>("NoticeCredDepID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CreditDebitMoney");

                    b.Property<float>("CreditorDebitStocks");

                    b.Property<int>("NoticeID");

                    b.Property<int>("PartnerID");

                    b.HasKey("NoticeCredDepID");

                    b.HasIndex("NoticeID");

                    b.HasIndex("PartnerID");

                    b.ToTable("NoticeDetails");
                });

            modelBuilder.Entity("DAL.Entities.Partner", b =>
                {
                    b.Property<int>("PartnerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConvertNumber")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CountryID");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdentityType");

                    b.Property<DateTime?>("IssueDate");

                    b.Property<string>("IssuePlace")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PartnerID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CountryID");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("DAL.Entities.Portfolio", b =>
                {
                    b.Property<int>("PortfolioID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("EstablishDate");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PartnerCount");

                    b.Property<decimal?>("PortfolioCapital")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("StockValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float?>("StocksCount");

                    b.HasKey("PortfolioID");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("DAL.Entities.PortfolioAccount", b =>
                {
                    b.Property<int>("PortfolioAccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<int>("PortfolioID");

                    b.Property<bool>("Type");

                    b.HasKey("PortfolioAccountID");

                    b.HasIndex("AccountID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("PortfolioAccounts");
                });

            modelBuilder.Entity("DAL.Entities.Portfolioshareholder", b =>
                {
                    b.Property<int>("PortShareID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("PartnerID");

                    b.Property<float>("Percentage");

                    b.Property<int>("PortfolioID");

                    b.Property<int>("StocksCount");

                    b.HasKey("PortShareID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("Portfolioshareholders");
                });

            modelBuilder.Entity("DAL.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date");

                    b.Property<int>("EmployeeID");

                    b.Property<int>("PortfolioID");

                    b.Property<int>("PurchaseWay");

                    b.HasKey("PurchaseID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("DAL.Entities.PurchaseOrderStock", b =>
                {
                    b.Property<int>("PurchaseStockID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BankCommittion");

                    b.Property<float>("BankCommittionRate");

                    b.Property<int>("PartnerID");

                    b.Property<int>("PurchaseID");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<int>("StockCount");

                    b.Property<decimal>("StockPrice");

                    b.Property<int>("TaxOnCommission");

                    b.Property<float>("TaxRateOnCommission");

                    b.Property<decimal>("TotalCost");

                    b.HasKey("PurchaseStockID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("PurchaseID");

                    b.ToTable("PurchaseOrderStocks");
                });

            modelBuilder.Entity("DAL.Entities.ReceiptExchange", b =>
                {
                    b.Property<int>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<DateTime?>("ChiqueDate");

                    b.Property<int?>("ChiqueNumber");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrencyID");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<bool>("Type");

                    b.HasKey("ReceiptID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CurrencyID");

                    b.ToTable("ReceiptExchanges");
                });

            modelBuilder.Entity("DAL.Entities.ReceiptExchangeDetail", b =>
                {
                    b.Property<int>("ReceiptExchangeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<int>("ChiqueNumber");

                    b.Property<decimal>("ReceiptExchangeAmount");

                    b.Property<bool>("Type");

                    b.HasKey("ReceiptExchangeID");

                    b.HasIndex("AccountID");

                    b.ToTable("ReceiptExchangeDetails");
                });

            modelBuilder.Entity("DAL.Entities.SellOrder", b =>
                {
                    b.Property<int>("SellID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date");

                    b.Property<int>("EmployeeID");

                    b.Property<int>("PortfolioID");

                    b.Property<int>("PurchaseWay");

                    b.HasKey("SellID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("SellOrders");
                });

            modelBuilder.Entity("DAL.Entities.SellOrderStock", b =>
                {
                    b.Property<int>("SellStockID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BankCommittion");

                    b.Property<float>("BankCommittionRate");

                    b.Property<int>("PartnerID");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<int>("SellID");

                    b.Property<int>("StockCount");

                    b.Property<decimal>("StockPrice");

                    b.Property<int>("TaxOnCommission");

                    b.Property<float>("TaxRateOnCommission");

                    b.Property<decimal>("TotalCost");

                    b.HasKey("SellStockID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("SellID");

                    b.ToTable("SellOrderStocks");
                });

            modelBuilder.Entity("DAL.Entities.Setting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AutoGenerateEntry");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DoNotGenerateEntry");

                    b.Property<bool>("GenerateEntry");

                    b.Property<int>("VoucherType");

                    b.HasKey("SettingID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DAL.Entities.SettingAccount", b =>
                {
                    b.Property<int>("SettingAccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<int>("AccountType");

                    b.Property<int>("SettingID");

                    b.HasKey("SettingAccountID");

                    b.HasIndex("AccountID");

                    b.HasIndex("SettingID");

                    b.ToTable("SettingAccounts");
                });

            modelBuilder.Entity("DAL.Entities.Account", b =>
                {
                    b.HasOne("DAL.Entities.Account")
                        .WithMany("SubAccounts")
                        .HasForeignKey("AccoutnParentID");
                });

            modelBuilder.Entity("DAL.Entities.EmployeeCard", b =>
                {
                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany("EmployeeCards")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.EntryDetail", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("EntryDetails")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.Notice", b =>
                {
                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany("Notices")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("Notices")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.NoticeDetail", b =>
                {
                    b.HasOne("DAL.Entities.Notice", "Notice")
                        .WithMany("NoticeDetails")
                        .HasForeignKey("NoticeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("NoticeDetails")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.Partner", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("Partners")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Country", "Country")
                        .WithMany("Partners")
                        .HasForeignKey("CountryID");
                });

            modelBuilder.Entity("DAL.Entities.PortfolioAccount", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("PortfolioAccounts")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioAccounts")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.Portfolioshareholder", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("Portfolioshareholders")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PurchaseOrderStock", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("PurchaseOrderStocks")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderStocks")
                        .HasForeignKey("PurchaseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.ReceiptExchange", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("ReceiptExchanges")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Currency", "Currency")
                        .WithMany("ReceiptExchanges")
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.ReceiptExchangeDetail", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("ReceiptExchangeDetails")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.SellOrder", b =>
                {
                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany("SellOrders")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("SellOrders")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.SellOrderStock", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("SellOrderStocks")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.SellOrder", "SellOrder")
                        .WithMany("SellOrderStocks")
                        .HasForeignKey("SellID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.SettingAccount", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("SettingAccounts")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Setting", "Setting")
                        .WithMany("SettingAccounts")
                        .HasForeignKey("SettingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
