// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(StocksContext))]
    partial class StocksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountCategory");

                    b.Property<int?>("AccountRefrence");

                    b.Property<bool>("AccountType");

                    b.Property<int?>("AccoutnParentID");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Credit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CreditOpenningBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("DebitLimit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("DebitOpenningBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("LinkedDBAccID");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(150)");

                    b.Property<float?>("StocksCredit");

                    b.Property<float?>("StocksDebit");

                    b.Property<string>("TaxNum")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Telex")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AccountID");

                    b.HasIndex("AccoutnParentID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DAL.Entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DAL.Entities.Currency", b =>
                {
                    b.Property<int>("CurrencyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("CurrencyValue");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PartName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("PartValue");

                    b.HasKey("CurrencyID");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("DAL.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("BankAccNum")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("BirthDate");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsInternal");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PassportProfession")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Religion");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DAL.Entities.EmployeeCard", b =>
                {
                    b.Property<int>("EmpCardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardType");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeID");

                    b.Property<DateTime?>("EndDate");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("IssueDate");

                    b.Property<string>("IssuePlace")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("RenewalDate");

                    b.HasKey("EmpCardId");

                    b.HasIndex("EmployeeID");

                    b.ToTable("EmployeeCards");
                });

            modelBuilder.Entity("DAL.Entities.Entry", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date");

                    b.Property<int?>("NoticeID");

                    b.Property<int?>("PurchaseInvoiceID");

                    b.Property<int?>("ReceiptID");

                    b.Property<int?>("RefrenceEntryId");

                    b.Property<int?>("SellingInvoiceID");

                    b.Property<bool>("TransferedToAccounts");

                    b.HasKey("EntryID");

                    b.HasIndex("NoticeID")
                        .IsUnique()
                        .HasFilter("[NoticeID] IS NOT NULL");

                    b.HasIndex("PurchaseInvoiceID")
                        .IsUnique()
                        .HasFilter("[PurchaseInvoiceID] IS NOT NULL");

                    b.HasIndex("ReceiptID")
                        .IsUnique()
                        .HasFilter("[ReceiptID] IS NOT NULL");

                    b.HasIndex("SellingInvoiceID")
                        .IsUnique()
                        .HasFilter("[SellingInvoiceID] IS NOT NULL");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("DAL.Entities.EntryDetail", b =>
                {
                    b.Property<int>("EntryDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<decimal?>("Credit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EntryID");

                    b.Property<float?>("StocksCredit");

                    b.Property<float?>("StocksDebit");

                    b.HasKey("EntryDetailID");

                    b.HasIndex("AccountID");

                    b.HasIndex("EntryID");

                    b.ToTable("EntryDetails");
                });

            modelBuilder.Entity("DAL.Entities.Notice", b =>
                {
                    b.Property<int>("NoticeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("DistributionDate");

                    b.Property<int>("EmployeeID");

                    b.Property<DateTime?>("NoticeDate");

                    b.Property<int>("PortfolioID");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Type");

                    b.HasKey("NoticeID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("DAL.Entities.NoticeDetail", b =>
                {
                    b.Property<int>("NoticeDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<decimal?>("Credit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NoticeID");

                    b.Property<int?>("PartnerID");

                    b.Property<float?>("StocksCredit");

                    b.Property<float?>("StocksDebit");

                    b.HasKey("NoticeDetailID");

                    b.HasIndex("AccountID");

                    b.HasIndex("NoticeID");

                    b.HasIndex("PartnerID");

                    b.ToTable("NoticeDetails");
                });

            modelBuilder.Entity("DAL.Entities.Partner", b =>
                {
                    b.Property<int>("PartnerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<decimal?>("Capital")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CommercialRegNo")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ConvertNumber")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CountryID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("IdentityType");

                    b.Property<DateTime?>("IssueDate");

                    b.Property<string>("IssuePlace")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TaxNo")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PartnerID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CountryID");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("DAL.Entities.PartnerAttachment", b =>
                {
                    b.Property<int>("PartnerAttachID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PartnerID");

                    b.HasKey("PartnerAttachID");

                    b.HasIndex("PartnerID");

                    b.ToTable("PartnerAttachments");
                });

            modelBuilder.Entity("DAL.Entities.Portfolio", b =>
                {
                    b.Property<int>("PortfolioID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("EstablishDate");

                    b.Property<string>("NameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(150)");

                    b.Property<float?>("TotalStocksCount");

                    b.HasKey("PortfolioID");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("DAL.Entities.PortfolioAccount", b =>
                {
                    b.Property<int>("PortfolioAccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<int>("PortfolioID");

                    b.Property<bool>("Type");

                    b.HasKey("PortfolioAccountID");

                    b.HasIndex("AccountID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("PortfolioAccounts");
                });

            modelBuilder.Entity("DAL.Entities.PortfolioOpeningStocks", b =>
                {
                    b.Property<int>("PortOPenStockID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("OpeningStockValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float>("OpeningStocksCount");

                    b.Property<int>("PartnerID");

                    b.Property<int>("PortfolioID");

                    b.HasKey("PortOPenStockID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("PortfolioOpeningStocks");
                });

            modelBuilder.Entity("DAL.Entities.PortfolioTransaction", b =>
                {
                    b.Property<int>("PortTransID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CurrentStockValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float>("CurrentStocksCount");

                    b.Property<int>("PartnerID");

                    b.Property<int>("PortfolioID");

                    b.HasKey("PortTransID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("PortfolioTransactions");
                });

            modelBuilder.Entity("DAL.Entities.PurchaseInvoice", b =>
                {
                    b.Property<int>("PurchaseInvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("EmployeeID");

                    b.Property<int>("PurchaseOrderID");

                    b.HasKey("PurchaseInvoiceID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PurchaseOrderID");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("DAL.Entities.PurchaseInvoiceDetail", b =>
                {
                    b.Property<int>("PurchaseInvoiceDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BankCommission")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float>("BankCommissionRate");

                    b.Property<decimal>("NetAmmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PartnerID");

                    b.Property<int>("PurchaseInvoiceID");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float>("StockCount");

                    b.Property<decimal>("TaxOnCommission")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float>("TaxRateOnCommission");

                    b.HasKey("PurchaseInvoiceDetailID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("PurchaseInvoiceID");

                    b.ToTable("PurchaseInvoiceDetails");
                });

            modelBuilder.Entity("DAL.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeID");

                    b.Property<DateTime>("OrderDate");

                    b.Property<bool>("OrderType");

                    b.Property<int>("PortfolioID");

                    b.HasKey("PurchaseOrderID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("DAL.Entities.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("PurchaseOrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PartnerID");

                    b.Property<int>("PriceType");

                    b.Property<int>("PurchaseOrderID");

                    b.Property<float>("StockCount");

                    b.Property<decimal?>("TradingValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PurchaseOrderDetailID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("PurchaseOrderID");

                    b.ToTable("PurchaseOrderDetails");
                });

            modelBuilder.Entity("DAL.Entities.ReceiptExchange", b =>
                {
                    b.Property<int>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ChiqueDate");

                    b.Property<int?>("ChiqueNumber");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Handling")
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("ReceiptExchangeType");

                    b.Property<decimal?>("RecieptValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Type");

                    b.HasKey("ReceiptID");

                    b.ToTable("ReceiptExchanges");
                });

            modelBuilder.Entity("DAL.Entities.ReceiptExchangeDetail", b =>
                {
                    b.Property<int>("ReceiptExchangeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<decimal?>("Credit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("DetailType");

                    b.Property<int>("ReceiptID");

                    b.HasKey("ReceiptExchangeID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ReceiptID");

                    b.ToTable("ReceiptExchangeDetails");
                });

            modelBuilder.Entity("DAL.Entities.ReportFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsDefault");

                    b.Property<string>("ReportNameAr");

                    b.Property<string>("ReportNameEn");

                    b.Property<int?>("ReportType");

                    b.Property<int?>("ReportTypeId");

                    b.HasKey("Id");

                    b.ToTable("ReportFiles");
                });

            modelBuilder.Entity("DAL.Entities.ReportSetting", b =>
                {
                    b.Property<int>("ReportSettingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CurrentDate");

                    b.Property<decimal>("DailyStockValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PartnerID");

                    b.Property<int>("PortfolioID");

                    b.HasKey("ReportSettingID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("ReportSettings");
                });

            modelBuilder.Entity("DAL.Entities.SellingInvoice", b =>
                {
                    b.Property<int>("SellingInvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("EmployeeID");

                    b.Property<int>("SellingOrderID");

                    b.HasKey("SellingInvoiceID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("SellingOrderID");

                    b.ToTable("SellingInvoices");
                });

            modelBuilder.Entity("DAL.Entities.SellingInvoiceDetail", b =>
                {
                    b.Property<int>("SellInvoiceDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BankCommission")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float>("BankCommissionRate");

                    b.Property<decimal>("NetAmmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PartnerID");

                    b.Property<decimal>("SelingValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SellingInvoiceID");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float>("StockCount");

                    b.Property<decimal>("TaxOnCommission")
                        .HasColumnType("decimal(10,2)");

                    b.Property<float>("TaxRateOnCommission");

                    b.HasKey("SellInvoiceDetailID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("SellingInvoiceID");

                    b.ToTable("SellingInvoiceDetails");
                });

            modelBuilder.Entity("DAL.Entities.SellingOrder", b =>
                {
                    b.Property<int>("SellingOrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeID");

                    b.Property<DateTime>("OrderDate");

                    b.Property<bool>("OrderType");

                    b.Property<int>("PortfolioID");

                    b.HasKey("SellingOrderID");

                    b.HasIndex("PortfolioID");

                    b.ToTable("SellingOrders");
                });

            modelBuilder.Entity("DAL.Entities.SellingOrderDetail", b =>
                {
                    b.Property<int>("SellOrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PartnerID");

                    b.Property<int>("PriceType");

                    b.Property<int?>("PurchaseOrderID");

                    b.Property<int>("SellingOrderID");

                    b.Property<float>("StockCount");

                    b.Property<decimal?>("TradingValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SellOrderDetailID");

                    b.HasIndex("PartnerID");

                    b.HasIndex("PurchaseOrderID");

                    b.HasIndex("SellingOrderID");

                    b.ToTable("SellingOrderDetails");
                });

            modelBuilder.Entity("DAL.Entities.Setting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AutoGenerateEntry");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("DoNotGenerateEntry");

                    b.Property<bool>("GenerateEntry");

                    b.Property<bool>("TransferToAccounts");

                    b.Property<int>("VoucherType");

                    b.HasKey("SettingID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DAL.Entities.SettingAccount", b =>
                {
                    b.Property<int>("SettingAccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID");

                    b.Property<int>("AccountType");

                    b.Property<int>("SettingID");

                    b.HasKey("SettingAccountID");

                    b.HasIndex("AccountID");

                    b.HasIndex("SettingID");

                    b.ToTable("SettingAccounts");
                });

            modelBuilder.Entity("DAL.Entities.SettingKiloConnection", b =>
                {
                    b.Property<int>("SettingKiloID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TimerJobStartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("SettingKiloID");

                    b.ToTable("SettingKiloConnections");
                });

            modelBuilder.Entity("DAL.Entities.TestTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TestTables");
                });

            modelBuilder.Entity("DAL.Entities.UserLog", b =>
                {
                    b.Property<int>("UserLogID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("MobileView");

                    b.Property<DateTime>("OperationDate");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserLogID");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DAL.Entities.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("Creationdate");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(250)");

                    b.ToTable("ApplicationUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("DAL.Entities.Account", b =>
                {
                    b.HasOne("DAL.Entities.Account")
                        .WithMany("SubAccounts")
                        .HasForeignKey("AccoutnParentID");
                });

            modelBuilder.Entity("DAL.Entities.EmployeeCard", b =>
                {
                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany("EmployeeCards")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.Entry", b =>
                {
                    b.HasOne("DAL.Entities.Notice", "Notice")
                        .WithOne("Entry")
                        .HasForeignKey("DAL.Entities.Entry", "NoticeID");

                    b.HasOne("DAL.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithOne("Entry")
                        .HasForeignKey("DAL.Entities.Entry", "PurchaseInvoiceID");

                    b.HasOne("DAL.Entities.ReceiptExchange", "ReceiptExchange")
                        .WithOne("Entry")
                        .HasForeignKey("DAL.Entities.Entry", "ReceiptID");

                    b.HasOne("DAL.Entities.SellingInvoice", "SellingInvoice")
                        .WithOne("Entry")
                        .HasForeignKey("DAL.Entities.Entry", "SellingInvoiceID");
                });

            modelBuilder.Entity("DAL.Entities.EntryDetail", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("EntryDetails")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.Notice", b =>
                {
                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany("Notices")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("Notices")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.NoticeDetail", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Notice", "Notice")
                        .WithMany("NoticeDetails")
                        .HasForeignKey("NoticeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("NoticeDetails")
                        .HasForeignKey("PartnerID");
                });

            modelBuilder.Entity("DAL.Entities.Partner", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("Partners")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Country", "Country")
                        .WithMany("Partners")
                        .HasForeignKey("CountryID");
                });

            modelBuilder.Entity("DAL.Entities.PartnerAttachment", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("PartnerAttachments")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PortfolioAccount", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("PortfolioAccounts")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioAccounts")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PortfolioOpeningStocks", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("PortfolioOpeningStocks")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioOpeningStocks")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PortfolioTransaction", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("PortfolioTransactions")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioTransactions")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PurchaseInvoice", b =>
                {
                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("PurchaseOrderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PurchaseInvoiceDetail", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("PurchaseInvoiceDetails")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseInvoiceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("DAL.Entities.Employee")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.PurchaseOrderDetail", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.ReceiptExchangeDetail", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany("ReceiptExchangeDetails")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.ReceiptExchange", "ReceiptExchange")
                        .WithMany("ReceiptExchangeDetails")
                        .HasForeignKey("ReceiptID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.ReportSetting", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("ReportSettings")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("ReportSettings")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.SellingInvoice", b =>
                {
                    b.HasOne("DAL.Entities.Employee", "Employee")
                        .WithMany("SellingInvoices")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.SellingOrder", "SellingOrder")
                        .WithMany("SellingInvoices")
                        .HasForeignKey("SellingOrderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.SellingInvoiceDetail", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("SellingInvoiceDetails")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.SellingInvoice", "SellingInvoice")
                        .WithMany("SellingInvoiceDetails")
                        .HasForeignKey("SellingInvoiceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.SellingOrder", b =>
                {
                    b.HasOne("DAL.Entities.Portfolio", "Portfolio")
                        .WithMany("SellingOrders")
                        .HasForeignKey("PortfolioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.SellingOrderDetail", b =>
                {
                    b.HasOne("DAL.Entities.Partner", "Partner")
                        .WithMany("SellingOrderDetails")
                        .HasForeignKey("PartnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.PurchaseOrder")
                        .WithMany("SellingOrderDetails")
                        .HasForeignKey("PurchaseOrderID");

                    b.HasOne("DAL.Entities.SellingOrder", "SellingOrder")
                        .WithMany("SellingOrderDetails")
                        .HasForeignKey("SellingOrderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.SettingAccount", b =>
                {
                    b.HasOne("DAL.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Setting", "Setting")
                        .WithMany("SettingAccounts")
                        .HasForeignKey("SettingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.UserLog", b =>
                {
                    b.HasOne("DAL.Entities.ApplicationUser", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
